# debug: true

logging:
  # 设置分组
  group:
    ebank: com.ruochen.controller,com.ruochen.service,com.ruochen.dao
    iservice: com.alibaba
  level:
    root: info
    # 设置某个包的日志级别
    # com.ruochen.controller.: debug
    # 设置分组，对某个组设置日志级别
    ebank: warn

