# debug: true

logging:
  # 设置分组
  group:
    ebank: com.ruochen.controller,com.ruochen.service,com.ruochen.dao
    iservice: com.alibaba
  level:
    root: info
    # 设置某个包的日志级别
    # com.ruochen.controller.: debug
    # 设置分组，对某个组设置日志级别
    ebank: warn

  # 日志输出格式
  pattern:
    # console: "%d - %m %n"
    # %d：日期  %n：换行   %m：日志信息
    # %5: 五位  %clr()：彩色
    # %p：日志级别
    # %t：线程名   %c：类名
    # %-40：40位左对齐   .40：内容截取
    # %clr(){cyan}：指定颜色
    console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"


