servers:
  # ipAddress: 192.168.0.1   # 驼峰
  # ipaddress: 192.168.0.1
  # ip_address: 192.168.0.1  # underline
  ip-address: 192.168.0.1    # 烤肉串模式
  # IPADDRESS: 192.168.0.1
  # IP_ADDRESS: 192.168.0.1  # 常量
  # IP_ADD_R_E_S_S: 192.168.0.1
  ipAddress: 192.168.0.1
  port: 2345
  timeout: -1

datasource:
  driverClassName: com.mysql.jdbc.Driver222