# Druid 配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm?useSSL=false&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: ruochen666
      maximum-pool-size: 50

# mp 表前缀
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tbl_
#      id-type: auto  # 数据库自增策略
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
